"""Transparent aggregate data-quality scoring for Sentinel Atlas."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date
from statistics import mean
from typing import Any, Mapping, Sequence

from .feature_availability import source_supports_country
from .normalization import NormalizedRecord, SourceDescriptor, coerce_date, normalize_iso3, normalize_source_descriptor


RELIABILITY_TIER_SCORES = {
    "official_public": 1.0,
    "official": 0.95,
    "government": 0.9,
    "academic_public": 0.85,
    "public_research": 0.85,
    "validated_partner": 0.8,
    "open_data": 0.75,
    "forecast_hub": 0.75,
    "news_public": 0.55,
    "user_added_validated": 0.55,
    "user_added_unvalidated": 0.35,
    "unknown": 0.3,
}

QUALITY_WEIGHTS = {
    "completeness": 0.20,
    "recency": 0.15,
    "reporting_lag": 0.10,
    "temporal_coverage": 0.15,
    "spatial_coverage": 0.10,
    "reliability_tier": 0.15,
    "uncertainty": 0.10,
    "country_coverage": 0.05,
}


@dataclass(frozen=True)
class QualityComponent:
    """One transparent data-quality score component."""

    name: str
    score: float
    weight: float
    rationale: str
    inputs: Mapping[str, Any] = field(default_factory=dict)
    warnings: tuple[str, ...] = ()


@dataclass(frozen=True)
class DataQualityReport:
    """Country-scoped aggregate data-quality report."""

    country_iso3: str
    as_of_date: date
    overall_score: float
    components: Mapping[str, QualityComponent]
    record_count: int
    source_ids: tuple[str, ...]
    warnings: tuple[str, ...] = ()
    limitations: tuple[str, ...] = ()


def assess_data_quality(
    country_iso3: str,
    records: Sequence[NormalizedRecord],
    sources: Sequence[SourceDescriptor | Mapping[str, object]] = (),
    *,
    as_of_date: date | str | None = None,
    expected_window_days: int = 90,
    expected_interval_days: int = 7,
) -> DataQualityReport:
    """Score aggregate data quality for a country without generating predictions."""

    country = normalize_iso3(country_iso3)
    if not country or country == "GLOBAL":
        raise ValueError("country_iso3 must be a concrete ISO3 country code")

    today = coerce_date(as_of_date) or date.today()
    normalized_sources = tuple(normalize_source_descriptor(source) for source in sources)
    source_by_id = {source.id: source for source in normalized_sources}
    country_records = tuple(record for record in records if record.country_iso3 == country)
    source_ids = _unique(tuple(record.source_id for record in country_records))

    warnings: list[str] = []
    limitations: list[str] = [
        "Scores describe aggregate data readiness only; they are not outbreak risk estimates.",
        "No model prediction, nowcast, or forecast is generated by this service.",
    ]

    if not country_records:
        warnings.append("No normalized aggregate records are available for this country.")

    components = {
        "completeness": score_completeness(country_records),
        "recency": score_recency(country_records, today),
        "reporting_lag": score_reporting_lag(country_records),
        "temporal_coverage": score_temporal_coverage(
            country_records,
            expected_window_days=expected_window_days,
            expected_interval_days=expected_interval_days,
        ),
        "spatial_coverage": score_spatial_coverage(country_records),
        "reliability_tier": score_reliability_tier(country_records, source_by_id),
        "uncertainty": score_uncertainty(country_records, source_ids),
        "country_coverage": score_country_coverage(country, country_records, normalized_sources),
    }

    overall = sum(component.score * component.weight for component in components.values())

    return DataQualityReport(
        country_iso3=country,
        as_of_date=today,
        overall_score=round(overall, 3),
        components=components,
        record_count=len(country_records),
        source_ids=source_ids,
        warnings=tuple(_unique(tuple(warnings))),
        limitations=tuple(limitations),
    )


def score_completeness(records: Sequence[NormalizedRecord]) -> QualityComponent:
    if not records:
        return QualityComponent(
            name="completeness",
            score=0.0,
            weight=QUALITY_WEIGHTS["completeness"],
            rationale="No records were available to inspect for required fields.",
            inputs={"record_count": 0},
        )

    required_present = 0
    required_total = len(records) * 5
    provenance_present = 0

    for record in records:
        required_present += sum(
            [
                bool(record.source_id),
                bool(record.country_iso3),
                bool(record.metric),
                bool(record.date),
                record.value is not None,
            ]
        )
        provenance_present += int(_has_provenance(record))

    required_score = required_present / required_total
    provenance_score = provenance_present / len(records)
    score = (required_score * 0.8) + (provenance_score * 0.2)

    return QualityComponent(
        name="completeness",
        score=round(score, 3),
        weight=QUALITY_WEIGHTS["completeness"],
        rationale="Required normalized fields are weighted with provenance coverage.",
        inputs={
            "records": len(records),
            "required_field_presence": round(required_score, 3),
            "provenance_presence": round(provenance_score, 3),
        },
    )


def score_recency(records: Sequence[NormalizedRecord], as_of_date: date) -> QualityComponent:
    latest = max((record.date for record in records), default=None)
    if latest is None:
        return QualityComponent(
            name="recency",
            score=0.0,
            weight=QUALITY_WEIGHTS["recency"],
            rationale="No latest observation date is available.",
            inputs={},
        )

    age_days = max((as_of_date - latest).days, 0)
    if age_days <= 14:
        score = 1.0
    elif age_days >= 90:
        score = 0.0
    else:
        score = 1.0 - ((age_days - 14) / 76.0)

    return QualityComponent(
        name="recency",
        score=round(score, 3),
        weight=QUALITY_WEIGHTS["recency"],
        rationale="Latest aggregate observation age is scored from fresh (<=14 days) to stale (>=90 days).",
        inputs={"latest_date": latest.isoformat(), "age_days": age_days},
    )


def score_reporting_lag(records: Sequence[NormalizedRecord]) -> QualityComponent:
    lags = []
    missing = 0
    for record in records:
        reported_or_ingested = record.reported_at or record.ingested_at or record.provenance.reported_at
        if not reported_or_ingested:
            missing += 1
            continue
        lags.append(max((reported_or_ingested - record.date).days, 0))

    if not records:
        return QualityComponent(
            name="reporting_lag",
            score=0.0,
            weight=QUALITY_WEIGHTS["reporting_lag"],
            rationale="No records were available to evaluate reporting lag.",
            inputs={"record_count": 0},
        )

    if not lags:
        return QualityComponent(
            name="reporting_lag",
            score=0.35,
            weight=QUALITY_WEIGHTS["reporting_lag"],
            rationale="Reporting or ingestion dates are missing, so lag is uncertain.",
            inputs={"record_count": len(records), "records_missing_lag_dates": missing},
            warnings=("Reporting lag dates are missing for all records.",),
        )

    avg_lag = mean(lags)
    if avg_lag <= 7:
        score = 1.0
    elif avg_lag <= 14:
        score = 0.8
    elif avg_lag <= 30:
        score = 0.55
    elif avg_lag <= 60:
        score = 0.25
    else:
        score = 0.0

    missing_penalty = (missing / len(records)) * 0.25
    score = max(score - missing_penalty, 0.0)

    return QualityComponent(
        name="reporting_lag",
        score=round(score, 3),
        weight=QUALITY_WEIGHTS["reporting_lag"],
        rationale="Average reporting lag is scored with a penalty for records lacking lag dates.",
        inputs={
            "average_lag_days": round(avg_lag, 2),
            "records_with_lag_dates": len(lags),
            "records_missing_lag_dates": missing,
        },
    )


def score_temporal_coverage(
    records: Sequence[NormalizedRecord],
    *,
    expected_window_days: int,
    expected_interval_days: int,
) -> QualityComponent:
    if not records:
        return QualityComponent(
            name="temporal_coverage",
            score=0.0,
            weight=QUALITY_WEIGHTS["temporal_coverage"],
            rationale="No records were available to evaluate temporal coverage.",
            inputs={"record_count": 0},
        )

    unique_dates = sorted({record.date for record in records})
    span_days = (unique_dates[-1] - unique_dates[0]).days + 1
    expected_points = max(int(expected_window_days / max(expected_interval_days, 1)), 1)
    span_score = min(span_days / expected_window_days, 1.0)
    density_score = min(len(unique_dates) / expected_points, 1.0)
    score = (span_score * 0.55) + (density_score * 0.45)

    return QualityComponent(
        name="temporal_coverage",
        score=round(score, 3),
        weight=QUALITY_WEIGHTS["temporal_coverage"],
        rationale="Coverage combines observed date span and expected point density.",
        inputs={
            "unique_dates": len(unique_dates),
            "span_days": span_days,
            "expected_window_days": expected_window_days,
            "expected_points": expected_points,
        },
    )


def score_spatial_coverage(records: Sequence[NormalizedRecord]) -> QualityComponent:
    if not records:
        return QualityComponent(
            name="spatial_coverage",
            score=0.0,
            weight=QUALITY_WEIGHTS["spatial_coverage"],
            rationale="No records were available to evaluate spatial coverage.",
            inputs={"record_count": 0},
        )

    admin1_count = len({record.admin1 for record in records if record.admin1})
    admin2_count = len({record.admin2 for record in records if record.admin2})
    named_locations = len({record.location_name for record in records if record.location_name})
    coordinate_count = sum(1 for record in records if record.latitude is not None and record.longitude is not None)

    country_level_score = 0.65
    admin_score = min((admin1_count * 0.08) + (admin2_count * 0.04), 0.25)
    location_score = min(named_locations * 0.02, 0.10)
    score = min(country_level_score + admin_score + location_score, 1.0)

    warnings = ()
    if coordinate_count:
        warnings = ("Coordinates should represent aggregate public locations only, never personal traces.",)

    return QualityComponent(
        name="spatial_coverage",
        score=round(score, 3),
        weight=QUALITY_WEIGHTS["spatial_coverage"],
        rationale="Country-level aggregate coverage is acceptable; subnational aggregate diversity adds confidence.",
        inputs={
            "admin1_count": admin1_count,
            "admin2_count": admin2_count,
            "location_count": named_locations,
            "records_with_coordinates": coordinate_count,
        },
        warnings=warnings,
    )


def score_reliability_tier(
    records: Sequence[NormalizedRecord],
    source_by_id: Mapping[str, SourceDescriptor],
) -> QualityComponent:
    if not records:
        return QualityComponent(
            name="reliability_tier",
            score=0.0,
            weight=QUALITY_WEIGHTS["reliability_tier"],
            rationale="No record sources were available to score reliability.",
            inputs={},
        )

    scores = []
    missing_sources = set()
    for record in records:
        source = source_by_id.get(record.source_id)
        if not source:
            scores.append(RELIABILITY_TIER_SCORES["unknown"])
            missing_sources.add(record.source_id)
            continue
        scores.append(reliability_score(source.reliability_tier, user_added=source.user_added))

    avg = mean(scores)
    warnings = ()
    if missing_sources:
        warnings = (f"Missing source metadata for: {', '.join(sorted(missing_sources))}.",)

    return QualityComponent(
        name="reliability_tier",
        score=round(avg, 3),
        weight=QUALITY_WEIGHTS["reliability_tier"],
        rationale="Reliability is the record-weighted average of source metadata tiers.",
        inputs={"source_ids": sorted({record.source_id for record in records})},
        warnings=warnings,
    )


def score_uncertainty(records: Sequence[NormalizedRecord], source_ids: Sequence[str]) -> QualityComponent:
    if not records:
        return QualityComponent(
            name="uncertainty",
            score=0.0,
            weight=QUALITY_WEIGHTS["uncertainty"],
            rationale="No records means uncertainty is high.",
            inputs={"record_count": 0, "estimated_uncertainty": 1.0},
        )

    sample_penalty = max(0.0, 1.0 - min(len(records) / 12.0, 1.0)) * 0.35
    source_penalty = max(0.0, 1.0 - min(len(source_ids) / 3.0, 1.0)) * 0.25
    provenance_penalty = max(0.0, 1.0 - (_provenance_ratio(records))) * 0.25
    metric_penalty = max(0.0, 1.0 - min(len({record.metric for record in records}) / 2.0, 1.0)) * 0.15
    estimated_uncertainty = min(sample_penalty + source_penalty + provenance_penalty + metric_penalty, 1.0)
    score = 1.0 - estimated_uncertainty

    return QualityComponent(
        name="uncertainty",
        score=round(score, 3),
        weight=QUALITY_WEIGHTS["uncertainty"],
        rationale="Higher score means lower uncertainty from sample size, source diversity, provenance, and metric diversity.",
        inputs={
            "record_count": len(records),
            "source_count": len(source_ids),
            "provenance_ratio": round(_provenance_ratio(records), 3),
            "metric_count": len({record.metric for record in records}),
            "estimated_uncertainty": round(estimated_uncertainty, 3),
        },
    )


def score_country_coverage(
    country_iso3: str,
    records: Sequence[NormalizedRecord],
    sources: Sequence[SourceDescriptor],
) -> QualityComponent:
    supported_sources = tuple(source for source in sources if source_supports_country(source, country_iso3))
    if not sources:
        score = min(len({record.source_id for record in records}) / 3.0, 1.0) * 0.6
        rationale = "No source catalog metadata was provided; score is based on distinct record sources only."
    else:
        metadata_score = len(supported_sources) / len(sources)
        record_score = min(len({record.source_id for record in records}) / 3.0, 1.0)
        score = (metadata_score * 0.55) + (record_score * 0.45)
        rationale = "Country coverage combines source catalog support and connected record-source diversity."

    return QualityComponent(
        name="country_coverage",
        score=round(min(score, 1.0), 3),
        weight=QUALITY_WEIGHTS["country_coverage"],
        rationale=rationale,
        inputs={
            "supported_source_count": len(supported_sources),
            "catalog_source_count": len(sources),
            "record_source_count": len({record.source_id for record in records}),
        },
    )


def reliability_score(reliability_tier: str | None, *, user_added: bool = False) -> float:
    if user_added and not reliability_tier:
        return RELIABILITY_TIER_SCORES["user_added_unvalidated"]
    tier = (reliability_tier or "unknown").strip().lower().replace(" ", "_")
    if user_added and tier == "unknown":
        tier = "user_added_unvalidated"
    return RELIABILITY_TIER_SCORES.get(tier, RELIABILITY_TIER_SCORES["unknown"])


def _has_provenance(record: NormalizedRecord) -> bool:
    return bool(
        record.provenance.source_url
        or record.provenance.raw_source
        or record.provenance.retrieved_at
        or record.provenance.reported_at
        or record.reported_at
        or record.ingested_at
    )


def _provenance_ratio(records: Sequence[NormalizedRecord]) -> float:
    if not records:
        return 0.0
    return sum(1 for record in records if _has_provenance(record)) / len(records)


def _unique(values: Sequence[str]) -> tuple[str, ...]:
    seen: set[str] = set()
    output: list[str] = []
    for value in values:
        if value in seen:
            continue
        seen.add(value)
        output.append(value)
    return tuple(output)


class DataQualityService:
    """Database-backed facade for API readiness endpoints."""

    def __init__(self, db) -> None:
        self.db = db

    def score_country_signal(self, country_iso3: str, signal_category: str, window_days: int = 90) -> dict[str, Any]:
        from app.services.feature_availability import _db_and_registry_sources, _db_records_for_country

        records = tuple(
            record
            for record in _db_records_for_country(self.db, country_iso3.upper())
            if _record_signal_category(record.source_id, record.metric) == signal_category
        )
        report = assess_data_quality(
            country_iso3.upper(),
            records,
            _db_and_registry_sources(self.db, country_iso3.upper()),
            expected_window_days=window_days,
        )
        components = report.components
        latest = max((record.date for record in records), default=None)
        return {
            "country_iso3": report.country_iso3,
            "signal_category": signal_category,
            "source_ids": list(report.source_ids),
            "record_count": report.record_count,
            "latest_observation_at": latest,
            "completeness_score": components["completeness"].score,
            "recency_score": components["recency"].score,
            "reporting_lag_score": components["reporting_lag"].score,
            "spatial_coverage_score": components["spatial_coverage"].score,
            "temporal_coverage_score": components["temporal_coverage"].score,
            "uncertainty_score": components["uncertainty"].score,
            "source_reliability_score": components["reliability_tier"].score,
            "overall_readiness_score": report.overall_score,
            "notes": "Transparent heuristic score for aggregate data readiness, not prediction validation.",
        }

    def observed_signal_categories(self, country_iso3: str) -> list[str]:
        from sqlalchemy import select

        from app.db import models

        return [
            row[0]
            for row in self.db.execute(
                select(models.Observation.signal_category)
                .where(models.Observation.country_iso3 == country_iso3.upper())
                .group_by(models.Observation.signal_category)
            ).all()
        ]

    def news_signal_count(self, country_iso3: str) -> int:
        from sqlalchemy import func, select

        from app.db import models

        return int(
            self.db.execute(
                select(func.count(models.NewsEvent.id)).where(models.NewsEvent.country_iso3 == country_iso3.upper())
            ).scalar_one()
        )


def _record_signal_category(source_id: str, metric: str) -> str:
    text = f"{source_id} {metric}".lower()
    if "wastewater" in text or "viral" in text or "copies" in text:
        return "wastewater"
    if "forecast" in text or "nowcast" in text:
        return "forecasts_nowcasts"
    if "news" in text or "event" in text:
        return "open_source_news"
    if "port" in text or "maritime" in text:
        return "maritime_ports_cargo"
    if "air" in text or "flight" in text or "mobility" in text:
        return "mobility"
    return "clinical_case_hospitalization"
